import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import Nav from "../UI/Nav";

interface props {
  children:
    | React.ReactNode
    | React.ReactNodeArray
    | React.ReactElement
    | React.ReactElement[]
    | string
    | null
    | undefined;
}

function LayoutMain({ children }: props) {
  const user = useUser();
  return (
    <>
      <Head>
        <title>Moter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav
        isSignedIn={user.isSignedIn}
        profileImageUrl={user.user?.profileImageUrl}
      />

      <main className="flex min-h-screen flex-col items-center  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex w-screen flex-row items-center justify-center gap-8 py-2">
          <h1 className="w-screen text-6xl text-white sm:text-2xl"></h1>
        </div>
        {children}
      </main>
    </>
  );
}

export default LayoutMain;
