import { SignUpButton, useUser } from "@clerk/nextjs";
import { Button } from "flowbite-react";
import { type NextPage } from "next";
import Head from "next/head";
import CreatePost from "~/components/UI/CreatePost";
import Nav from "~/components/UI/Nav";
import PostList from "~/components/UI/PostList";

const Home: NextPage = () => {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Moter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user.isSignedIn && (
        <Nav
          isSignedIn={user.isSignedIn}
          profileImageUrl={user.user?.profileImageUrl}
        />
      )}
      <main className="flex min-h-screen flex-col items-center  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex flex-row items-center justify-center gap-8 py-2">
          <h1 className="text-6xl text-white sm:text-2xl">
            Hola {user.user?.firstName}
          </h1>
          {!user.isSignedIn && (
            <SignUpButton mode="modal">
              <Button>Sign up</Button>
            </SignUpButton>
          )}
          {user.isSignedIn && (
            <>
              <CreatePost />
            </>
          )}
        </div>
        <PostList />
      </main>
    </>
  );
};

export default Home;
