import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { Button } from "flowbite-react";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.post.getAll.useQuery();
  const user = useUser();

  return (
    <>
      <Head>
        <title>Moter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          <h1 className="text-6xl font-bold text-white">Moter</h1>
          {
            <h1 className="font-bold text-white">
              hola {user.user?.firstName}
            </h1>
          }
          {!user.isSignedIn && (
            <SignInButton mode="modal">
              <Button color="purple">Login</Button>
            </SignInButton>
          )}
          {user.isSignedIn && (
            <div>
              <div>
                {user.user?.profileImageUrl && (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={user.user?.profileImageUrl}
                    alt="profile"
                    className="h-20 w-20 rounded-full"
                  />
                )}
              </div>
              <SignOutButton>
                <Button color="purple">Logout</Button>
              </SignOutButton>
              {data?.map((post) => (
                <div key={post.id}>{post.content}</div>
              ))}
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
